# ruff.toml

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
line-length = 88
indent-width = 4

[format]
quote-style = "double"
indent-style = "space"
exclude = ["**/migrations/*.py"]
[lint]
select = [
    "E", # pycodestyle
    "F", # flake8
    "I", # isort 
]

[lint.per-file-ignores]
"__init__.py" = ["F401", "E402"]
"settings.py" = ["E501"]
"**/migrations/*.py" = ["E501"]
[lint.isort]
known-first-party = ["api", "tasks", "users", "task_tracker"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]